### ISSUE TITLE
How to install it using Cocoapods ?

### ISSUE THREAD

**Issue by X901** [jyunderwood/WaveformView-iOS#5]
Hi ,

I noticed in your example you are using Cocoapods

but in ReadME file you don't mention how to install it using Cocoapods !!

**Comment by jyunderwood** [comment]
The example isn't using cocoapods; it's using [Carthage](https://github.com/Carthage/Carthage).

Cocoapods support is something I've thought about adding for others, but dependancies in my personal projects are managed with Carthage.

If you're familiar with Cocoapods, feel free to submit a PR that adds Cocoapods support.

**Comment by X901** [comment]
After I install it using Carthage 

I got this error :

` Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1`

**Comment by jyunderwood** [comment]
Ah, yes. Swift moves pretty fast. I just created a swift-3.1 branch. Try this in your Carthage file to use the Swift 3.1 branch:

```
github "jyunderwood/WaveformView-iOS" "swift-3.1"
```

**Comment by X901** [comment]
I got same error =(

**Comment by jyunderwood** [comment]
After you've updated your Cartfile with the above, you need to update your builds. Also, to make sure you are compiling from source, pass `--no-use-binaries`.

```
carthage update --platform iOS --no-use-binaries
```

Also, Since you're running a beta version of Xcode, make sure your command line Swift is set to the 3.1 beta: `xcrun swift -version`.

I'm going to close this issue because it doesn't seem to be an issue with the project, but with your build chain. If you're still running in to issues, you might want to look on StackOverflow on help using Carthage with a beta version of Xcode.
