### ISSUE TITLE
How to rest the waves in beginning ? can I use it with AVplayer ?

### ISSUE THREAD

**Issue by X901** [jyunderwood/WaveformView-iOS#6]
Hi , 

I want the waves to be as "one" line not as waves in the beginning 
I have a button to record voice when I click on it , it will start recording 
but the problem is before I click on it the library display the view as waves 

I hope you understand my issue 

Another thing is how to use it with Playing Audio using AVplayer or AVAudioPlayer ?

**Comment by jyunderwood** [comment]
The default state of the wave is set to 0.3 so you can see the waves in Interface Builder instead of just a straight line. Use `updateWithLevel(_ level: CGFloat)` to set the wave. 0.0 is a line.

As far as playing audio, I used AVAudioRecorder for the example app, but AVAudioPlayer has an [`averagePower`](https://developer.apple.com/reference/avfoundation/avaudioplayer/1390838-averagepower) method, too.

If you look through the [example viewcontroller](https://github.com/jyunderwood/WaveformView-iOS/blob/master/Example-iOS/Example-iOS/ViewController.swift) to see how I used the audio recorder, you should be able to use roughly the same pattern for audio player.

If you want, please write some documentation and submit a PR or if you need additional properties or methods exposed, submit a PR and I'll take a look. Otherwise, you'll need to refer to the Apple documentation for how to use AVAudioPlayer.

**Comment by X901** [comment]
Thank you , I try it with AVAudioPlayer ,
I noticed The Waves is not exactly as how it were during recording 
What is the reason ?

**Comment by jyunderwood** [comment]
Not sure. The method to control the wave is the same regardless and only takes a float. You might want to try using a different channel, making sure you set the correct category for avaudiosession, or playing with the gain.
